name: Install

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B install
      - name: Codecov Scan
        uses: codecov/codecov-action@v1.0.4
        with:
          token: ${{ secrets.codecov_token }}
      - name: SonarCloud Scan
        run: mvn -B sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}
